import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Todo App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <div className='bg-indigo-900 min-h-screen antialiased tracking-tight'>
          <div className='mx-[10vw]'>
            <header className='flex justify-between'>
              <a href='/' className='py-10 text-indigo-100 text-3xl font-semibold'>
                Todo App ✅
              </a>
              <div className='py-10 text-lg'>
                <button className='btn mx-4 border px-4 py-2 rounded-xl duration-300 bg-indigo-900 text-indigo-100 font-semibold hover:bg-indigo-800 hover:text-indigo-200'>
                  Login
                </button>
                <button className='btn border px-4 py-2 rounded-xl duration-300 bg-indigo-100 text-indigo-900 font-semibold hover:bg-indigo-200 hover:text-indigo-800'>
                  Sign Up
                </button>
              </div>
            </header>
            <div className='flex justify-center'>{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
